---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo-mongo-svc
spec:
  ports:
  - name: http
    port: 81
    protocol: TCP
    targetPort: 3001
  selector:
    app: demo-mongo
  type: LoadBalancer
